name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flox
        uses: flox/install-flox-action@v2

      - name: Start services and run tests
        uses: flox/activate-action@v1
        with:
          command: |
            flox services start postgres
            pytest
